# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-09 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('subject', models.CharField(max_length=20)),
                ('complaint', models.CharField(max_length=150)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_message', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
