# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-09 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_userid', models.IntegerField()),
                ('to_userid', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('to_amount', models.IntegerField()),
            ],
        ),
    ]
